def writio = null

pipeline {
    agent any
    parameters {
        booleanParam(name: 'parameterization', defaultValue: false, description: 'If checked, a dry run is performed to initialize parameters')
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('initialize') {
            when {
                expression { true }
            }
            steps {
                script {

                    configFileProvider([configFile(fileId: "writio-config", variable: 'WRITIO_CONFIG')]) {
                        writio = readJSON file: "${env.WRITIO_CONFIG}"
                    }

                    if ("${params.parameterization}" == 'true') {
                        currentBuild.result = 'aborted'
                        error('dry run completed, job parameterized')
                    }
                }
            }
        }
        stage('build') {
            when {
                expression { true }
            }
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
