pipeline {
	agent {
		docker {
			image "maven:amazoncorretto"
			args "-v writio_ci_maven_repository:/root/.m2/repository"
			reuseNode true
		}
	}
	stages {
		stage('mvn-clean-install') {
			steps {
				sh "mvn clean install"
			}
		}
		stage('mvn-deploy') {
			steps {
				sh "mvn deploy"
			}
		}
	}
}