def repositoryUrl = 'https://github.com/cbehrenberg/writio.git'
def defaultBranch = 'dev'

pipeline {
    parameters {
        gitParameter(branchFilter: 'origin/(.*)', defaultValue: defaultBranch, name: 'branch', type: 'PT_BRANCH', description: "writio branch to build")
        booleanParam(name: 'parameterization', defaultValue: false, description: 'If checked, a dry run is performed to initialize parameters')
    }
    agent any
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('clean') {
            steps {
                step([$class: 'WsCleanup'])
            }
        }
        stage('parameterization') {
            steps {
                script {
                    if ("${params.parameterization}" == 'true') {
                        currentBuild.result = 'aborted'
                        error('dry run completed, job parameterized')
                    }
                }
            }
        }    
        stage('clone') {
            steps {
                echo "cloning git branch '${params.branch}'..."
                git branch: "${params.branch}", changelog: false, poll: false, url: repositoryUrl
            }
        }
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}