def writio = null

pipeline {
    parameters {
        gitParameter(branchFilter: 'origin/(.*)', defaultValue: "dev", name: 'branch', type: 'PT_BRANCH', description: "writio branch to build")
        booleanParam(name: 'parameterization', defaultValue: false, description: 'If checked, a dry run is performed to initialize parameters')
    }
    agent any
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('initialize') {
            when {
                expression { true }
            }
            steps {
                script {

                    step([$class: 'WsCleanup'])

                    configFileProvider([configFile(fileId: "writio-config", variable: 'WRITIO_CONFIG')]) {
                        writio = readJSON file: "${env.WRITIO_CONFIG}"
                    }

                    if ("${params.parameterization}" == 'true') {
                        currentBuild.result = 'aborted'
                        error('dry run completed, job parameterized')
                    }
                }
            }
        }
        stage('clone') {
            when {
                expression { true }
            }
            steps {
                git branch: "${params.branch}", changelog: false, poll: false, url: writio.repositoryUrl
            }
        }
        stage('build') {
            when {
                expression { true }
            }
            steps {
                sh 'mvn clean install'
            }
        }
        stage('archive') {
            when {
                expression { true }
            }
            steps {
                archiveArtifacts artifacts: 'api/target/classes/writio*.proto', fingerprint: true
                archiveArtifacts artifacts: 'app/epub-json-file/target/epub-json-file*.jar', fingerprint: true
            }
        }
    }
}