def config = null

pipeline {
    parameters {
        gitParameter(branchFilter: 'origin/(.*)', defaultValue: "dev", name: 'branch', type: 'PT_BRANCH', description: "writio branch to build")
        booleanParam(name: 'parameterization', defaultValue: false, description: 'If checked, a dry run is performed to initialize parameters')
    }
    agent any
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('clean') {
            when {
                expression { true }
            }
            steps {
                step([$class: 'WsCleanup'])
            }
        }
        stage('parameterization') {
            when {
                expression { true }
            }
            steps {
                script {

                    configFileProvider([configFile(fileId: "writio-config", variable: 'WRITIO_CONFIG')]) {
                        config = readJSON file: "${env.WRITIO_CONFIG}"
                    }

                    if ("${params.parameterization}" == 'true') {
                        currentBuild.result = 'aborted'
                        error('dry run completed, job parameterized')
                    }
                }
            }
        }    
        stage('clone') {
            when {
                expression { true }
            }
            steps {
                echo "cloning git branch '${params.branch}'..."
                git branch: "${params.branch}", changelog: false, poll: false, url: config.repositoryUrl
            }
        }
        stage('build') {
            when {
                expression { true }
            }
            steps {
                sh 'mvn clean install'
            }
        }
    }
}