pipeline {
	agent {
		docker {
			image 'maven:amazoncorretto'
			args '-v /maven/.m2:/root/.m2'
		}
	}
	stages {
		stage('clean') {
			steps {
				sh 'mvn clean'
			}
		}
		stage('package') {
			steps {
				sh 'mvn package'
			}
		}
		stage('install') {
			steps {
				sh 'mvn install'
			}
		}
	}
}