pipeline {
	parameters {
		gitParameter branchFilter: 'origin/(.*)', defaultValue: 'dev', name: 'BRANCH', type: 'PT_BRANCH'
	}
	agent {
		docker {
			image 'maven:amazoncorretto'
			args '-v /root/.m2:/root/.m2'
		}
	}
	stages {
		stage('git-checkout') {
			steps {
				echo "checking out git branch '${params.BRANCH}'..."
				git branch: "${params.BRANCH}", changelog: false, credentialsId: 'github-cbehrenberg', poll: false, url: 'https://github.com/cbehrenberg/writio.git'
			}
		}
		stage('mvn-clean-package') {
			steps {
				sh 'mvn clean package'
			}
		}
		stage('mvn-install') {
			steps {
				sh 'mvn install'
			}
		}
	}
}