pipeline {
	parameters {
		gitParameter branchFilter: 'origin/(.*)', defaultValue: 'dev', name: 'BRANCH', type: 'PT_BRANCH'
	}
	agent {
		docker {
			image "writio/maven:latest"
			args "-v /maven_repository:/maven_repository"
			reuseNode true
		}
	}
	stages {
		stage('git-checkout') {
			steps {
				echo "checking out git branch '${params.BRANCH}'..."
				git branch: "${params.BRANCH}", changelog: false, poll: false, url: 'https://github.com/cbehrenberg/writio.git'
			}
		}
		stage('mvn-clean-install') {
			steps {
				sh "mvn clean install -Dmaven.repo.local=/maven_repository -X"
			}
		}
	}
}